### ISSUE TITLE
Etna RealPlume slightly offset

### ISSUE THREAD

**Issue by coyotesfrontier** [ChrisAdderley/CryoEngines#64]
This is really only noticable if you change the Etna's plume type to something other then the default, but it's there on the original configuration as well. It seemingly has to do with an offset transform in Unity, as changing every variable in the configs to 0 doesn't fix it.

Tested on KSP 1.7.3, no mods other then CryoEngines and RealPlume (and their dependencies).

https://imgur.com/a/fdUHNar

**Comment by zorg2044** [comment]
I don't know how I missed this :( 

That said I took a quick look at the transforms position using debug tools and it appears to me everything is lined up. So not really sure why its happened. The plume on this engine is applied to fxTransformPlume (all the others directly to thrusTransform).

If @ChrisAdderley can verify that the transforms are all correct I can reposition this for the next update.

**Comment by ChrisAdderley** [comment]
Checked in unity, they're all perfectly zeroed.

**Comment by zorg2044** [comment]
Could be some kind of smokescreen issue I guess, I'll see whats up soon as I can. If no additional weirdness is present should just be a simple re-positioning.

**Comment by zorg2044** [comment]
New pull request should fix it. 

Problem was that I applied to the FX transforms instead of the thrustTransform as is typical (due to the name being used for both the main engine and the vernier). However in Smokescreen the plumes applied to the FXtransform ended up rotated 90 degrees, no idea why. When rotating to correct this, my new Y axis is the second number in local position rather than the third, missed this when writing the config.

https://github.com/ChrisAdderley/CryoEngines/pull/65

**Comment by ChrisAdderley** [comment]
Resolved in latest release version.
